version: '3.8'
services:

  prices:
    build: ..
    environment:
      - PGHOST=host.docker.internal
      - PGPORT=5433
      - PGDATABASE=prices
      - PGUSER=prices 
      - PGPASSWORD=prices
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=prices
      - POSTGRES_PASSWORD=prices
      - POSTGRES_USER=prices
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"

volumes:
  db-data:
