version: "3"
services:
    web:
        image: nginx:1.21.6
        container_name: hp_nginx
        restart: always
        links:
            - site
        volumes:
            - ./server.conf:/etc/nginx/conf.d/default.conf
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./data/logs:/logs
            - ..:/heisse-preise-de
        networks:
            - hp_network
    site:
        build:
            dockerfile: Dockerfile.site
            context: .
        container_name: hp_site
        restart: always
        volumes:
            - ..:/heisse-preise-de
            - ./data/:/heisse-preise-de/data
        networks:
            - hp_network

networks:
    hp_network:
        driver: bridge
