name: Test and Build

on: [push]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: github.ref == 'refs/heads/main'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t ghcr.io/yobst/yobst-scrapter:latest 
          docker push ghcr.io/yobst/yobst-scraper:latest
